import Header from "./header";
import styles from "./styles/main.module.css";
import { Outfit } from "next/font/google";

const outfit = Outfit({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Editor App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Header />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
