"use client";
import { Outfit } from "next/font/google";
import { EditorContext, useEditorGlobalState } from "../context/editor-context";
const outfit = Outfit({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Editor App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <EditorContext.Provider value={useEditorGlobalState()}>
            {children}
          </EditorContext.Provider>
        </main>
      </body>
    </html>
  );
}
