"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./lib/registry";
import { EditorContext, useEditorGlobalState } from "./context/editor-context";

const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EditorContext.Provider value={useEditorGlobalState()}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </EditorContext.Provider>
      </body>
    </html>
  );
}
