"use client";
import { EditorContext, useEditorGlobalState } from "../context/editor-context";

export const metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <EditorContext.Provider value={useEditorGlobalState()}>
          {children}
        </EditorContext.Provider>
      </body>
    </html>
  );
}
